### ISSUE TITLE
Build breakage

### ISSUE THREAD

**Issue by miscco** [sanjayankur31/xppaut#2]
Hey,

for me the build breaks during linking  with:

```
Linking C executable xppaut
/usr/bin/ld: CMakeFiles/xppaut.dir/extra.c.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

The strange thing is, that -lm and -ldl should actually do the trick

**Comment by miscco** [comment]
Ah ok, it seems that "-lm -ldl" is missing for the linker.

changing

``` cmake
set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "")
```

into

``` cmake
set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "-lm -ldl")
```

did the trick for me

**Comment by sanjayankur31** [comment]
Thanks for letting me know. Weird that it built on my Fedora system - Fedora has a policy against dynamic DSO linkages. I'll look into it.
